package ru.evo.tests;

import ru.evo.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Проверка поиска справочного центра")
    void generatedTest() {
        step("Открыть 'https://support.evotor.ru/hc/ru'", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить наличие текста на странице 'Мы поможем'", () -> {
            step("// todo: just add selenium action");
        });

        step("Ввести в поисковую строку 'Частичная инвентаризация'", () -> {
            step("// todo: just add selenium action");
        });

        step("Нажать Enter", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить, что в результатах поиска есть блок с названием 'База знаний'", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить, что в блоке База знаний есть результат с названием 'Частичная инвентаризация'", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://support.evotor.ru/hc/ru'", () ->
            open("https://support.evotor.ru/hc/ru"));

        step("Page title should have text 'Security check'", () -> {
            String expectedTitle = "Security check";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://support.evotor.ru/hc/ru'", () ->
            open("https://support.evotor.ru/hc/ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}